import { test } from "node:test";
import assert from "node:assert/strict";
import { importDdl, DdlImportError } from "@/lib/importers/ddl";
import { parseArchitectureDiagram } from "@/lib/architecture/parse";

/**
 * Epic 4 (SQL DDL importer) contract tests.
 * Generated erDiagrams must round-trip through the canonical parser.
 */

const POSTGRES_DDL = `
-- schema dump
CREATE TABLE IF NOT EXISTS public.users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

/* join table */
CREATE TABLE orders (
    id          SERIAL PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE shipments (
    id      BIGINT PRIMARY KEY,
    carrier VARCHAR(64) NOT NULL
);

ALTER TABLE orders
    ADD CONSTRAINT fk_order_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (id);
`;

const MYSQL_DDL = `
CREATE TABLE \`shipments\` (
  \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  \`carrier\` VARCHAR(64) NOT NULL DEFAULT 'post',
  \`tracking_code\` VARCHAR(128),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uq_tracking\` (\`tracking_code\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE \`parcels\` (
  \`id\` INT NOT NULL,
  \`weight_grams\` INT NOT NULL,
  \`fragile\` TINYINT(1) NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`fk_parcels_shipment\` FOREIGN KEY (\`shipment_id\`) REFERENCES \`shipments\` (\`id\`)
) ENGINE=InnoDB;
`;

test("imports PostgreSQL DDL: identity PKs, inline FKs, ALTER TABLE FKs", () => {
  const result = importDdl(POSTGRES_DDL);
  assert.equal(result.stats.tables, 3); // users, orders (+ shipments implied by ALTER)
  assert.ok(result.stats.columns >= 8);

  const parsed = parseArchitectureDiagram(result.erMermaid);
  assert.equal(parsed.error, null);

  const users = parsed.architecture.nodes.find((n) => n.name === "users");
  assert.ok(users, "users table exists");
  const idAttr = users.attributes.find((a) => a.name === "id");
  assert.ok(idAttr?.isPrimaryKey, "inline PRIMARY KEY honoured");
  const email = users.attributes.find((a) => a.name === "email");
  assert.ok(email?.isUnique, "inline UNIQUE honoured");
  const createdAt = users.attributes.find((a) => a.name === "created_at");
  assert.ok(createdAt && createdAt.type.includes("timestamp"), "multi-word types normalised");

  // Inline FK creates a reference edge parent -> child, many on the child side.
  const fkEdge = parsed.architecture.relationships.find((r) => r.source === "users" && r.target === "orders");
  assert.ok(fkEdge, "inline REFERENCES creates an edge");
  assert.equal(fkEdge.targetMultiplicity, "1..*", "NOT NULL FK is mandatory-many");

  // ALTER TABLE ADD FOREIGN KEY wires the shipment edge and materialises the column.
  const shipmentEdge = parsed.architecture.relationships.find(
    (r) => r.source === "shipments" && r.target === "orders"
  );
  assert.ok(shipmentEdge, "ALTER TABLE FK becomes an edge");
});

test("imports MySQL DDL: backticks, ENGINE tails, table-level constraints", () => {
  const result = importDdl(MYSQL_DDL);
  assert.deepEqual(
    result.stats.tables >= 2,
    true,
    `both tables found (${JSON.stringify(result.stats)})`
  );

  const parsed = parseArchitectureDiagram(result.erMermaid);
  assert.equal(parsed.error, null);

  const shipments = parsed.architecture.nodes.find((n) => n.name === "shipments");
  assert.ok(shipments);
  assert.ok(shipments.attributes.find((a) => a.name === "id")?.isPrimaryKey);
  const tracking = shipments.attributes.find((a) => a.name === "tracking_code");
  assert.ok(tracking?.isUnique, "table-level UNIQUE KEY name (col) honoured");
  // Nullability itself cannot survive Mermaid ER text (no grammar marker);
  // it is only reflected in cardinality: nullable FK -> optional-many.
  void tracking;

  const parcelsFk = parcelsEdge(parsed);
  assert.ok(parcelsFk, "CONSTRAINT ... FOREIGN KEY creates the edge");
  function parcelsEdge(parsed: ReturnType<typeof parseArchitectureDiagram>) {
    return parsed.architecture.relationships.find((r) => r.source === "shipments" && r.target === "parcels");
  }
});

test("nullable FKs are optional-many; composite PKs mark every column", () => {
  const ddl = `
  CREATE TABLE a (id INT PRIMARY KEY);
  CREATE TABLE b (
    id INT,
    a_id INT NULL,
    other_id INT NOT NULL,
    PRIMARY KEY (id, other_id),
    FOREIGN KEY (a_id) REFERENCES a (id)
  );`;
  const result = importDdl(ddl);
  const parsed = parseArchitectureDiagram(result.erMermaid);
  assert.equal(parsed.error, null);

  const tableB = parsed.architecture.nodes.find((n) => n.name === "b");
  assert.ok(tableB?.attributes.find((a) => a.name === "id")?.isPrimaryKey);
  assert.ok(tableB?.attributes.find((a) => a.name === "other_id")?.isPrimaryKey);

  const edge = parsed.architecture.relationships.find((r) => r.source === "a" && r.target === "b");
  assert.ok(edge);
  assert.equal(edge.targetMultiplicity, "0..*", "nullable FK allows no match");
});

test("schema-qualified names, comments and noise are stripped", () => {
  const ddl = `
  -- header comment
  /* block
     comment */
  CREATE TABLE inventory.items (
    item_id UUID PRIMARY KEY, -- trailing comment # not mysql-only
    label TEXT
  );`;
  const parsed = parseArchitectureDiagram(importDdl(ddl).erMermaid);
  assert.equal(parsed.error, null);
  assert.ok(parsed.architecture.nodes.some((n) => n.name === "items"));
});

test("rejects garbage and empty scripts with actionable errors", () => {
  assert.throws(() => importDdl(""), DdlImportError);
  assert.throws(() => importDdl("SELECT 1;"), DdlImportError);
  assert.throws(() => importDdl("CREATE INDEX idx ON t (c);"), DdlImportError);
});
